# Generated by Django 3.1.1 on 2021-01-08 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_scraper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('date', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=150)),
                ('short_desciption', models.CharField(max_length=150)),
                ('responses', models.CharField(max_length=150)),
                ('read_time', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Blog Model',
            },
        ),
        migrations.DeleteModel(
            name='TheodoTeam',
        ),
    ]
