# Generated by Django 3.1.1 on 2021-01-08 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_scraper', '0002_auto_20210108_0722'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
