# Generated by Django 3.1.1 on 2021-01-11 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_scraper', '0005_auto_20210110_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='read_time',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='responses',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='short_desciption',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
